spring:
  application:
    name: spring-ai-demo
  main:
    banner-mode: off
  sql:
    init:
      mode: always
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred #If you have many repositories, consider using deferred repository initialization:
        enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      # needs to be set to true for Spring AI to work (vector store, chat memory etc)
      auto-commit: true
      connection-test-query: select 1
      connection-timeout: 10000
      idle-timeout: 60000
      max-lifetime: 1800000
      maximum-pool-size: 50
      minimum-idle: 1
      pool-name: tomConnectionPooling
      transaction-isolation: TRANSACTION_READ_COMMITTED
      username: ${postgres.user:postgres}
      password: ${postgres.password:postgres}
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 512
        prepStmtCacheSqlLimit: 2048
        #serverTimezone: UTC # defaults to JVM setting either explicitly set or inherited from OS
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${postgres.host:localhost}:${postgres.port:5432}/${postgres.db:spring-ai-demo}?reWriteBatchedInserts=true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
    properties:
      hibernate:
        batch_versioned_data: true
        check_nullability: false
        connection:
          # Sources
          # https://vladmihalcea.com/spring-transaction-connection-management
          # https://vladmihalcea.com/why-you-should-always-use-hibernate-connection-provider_disables_autocommit-for-resource-local-jpa-transactions/
          # handling_mode: DELAYED_ACQUISITION_AND_RELEASE_AFTER_STATEMENT
          provider_disables_autocommit: true
        jdbc:
          batch_size: 100
        format_sql: true
        order_inserts: true
        order_updates: true
        query:
          in_clause_parameter_padding: true
          # Disable query validation at startup
          startup_check: false
          # Every JPQL query or Criteria query is parsed into an Abstract Syntax Tree (AST) prior to execution so that Hibernate can generate the SQL statement
          plan_cache_max_size: 4096
          plan_parameter_metadata_max_size: 512
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 1000
    show-sql: false
  ai:
    #    openai:
    #      api-key: ${OPENAI_API_KEY}
    #      # Use only if you route through an internal gateway / proxy:
    #      base-url: ${OPENAI_BASE_URL:https://api.openai.com}
    #      # Optional metadata headers (only if your environment needs them)
    #      # organization-id: ${OPENAI_ORG:}
    #      # project-id: ${OPENAI_PROJECT:}
    #      chat:
    #        options:
    #          # Pin a model explicitly (choose what you actually use)
    #          model: ${OPENAI_CHAT_MODEL:gpt-4.1-mini}
    #          temperature: ${OPENAI_TEMPERATURE:0.2}
    #          # If your Spring AI version supports it:
    #          max-tokens: ${OPENAI_MAX_TOKENS:800}
    #          # top-p: ${OPENAI_TOP_P:1.0}
    model:
      embedding: ollama
    ollama:
      base-url: http://localhost:11434
      init:
        pull-model-strategy: never
        timeout: 5m
        max-retries: 0
      chat:
        options:
          model: llama3.2:3b
          num-ctx: 4096 # input context window
          num-predict: 256 # max generated tokens
          temperature: 0.7
          keep-alive: 15m
          ### Sampling controls (Top-K and Top-P)
          # Nucleus sampling
          top-p: 0.8
          # Top-k sampling, restricts sampling to the top K most likely next tokens.
          top-k: 40
      embedding:
        options:
          model: nomic-embed-text # alt. mxbai-embed-large
          keep-alive: 15m

    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
            schema: classpath:memory-schema.sql
    vectorstore:
      pgvector:
        initialize-schema: false
        schema-name: public
        table-name: vector_store
        index-type: hnsw
        distance-type: cosine_distance
        dimensions: 768
        schema-validation: true
  threads:
    virtual:
      enabled: true
  lifecycle:
    timeout-per-shutdown-phase: 1m

logging:
  level:
    root: INFO
    gr.codelearn: TRACE
    org.springframework: INFO
    org.springframework.ai: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE