spring:
  application:
    name: spring-ai-demo
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${postgres.host:localhost}:${postgres.port:5432}/${postgres.db:spring-ai-demo}?reWriteBatchedInserts=true
    username: ${postgres.user:postgres}
    password: ${postgres.password:postgres}
  ai:
    #    openai:
    #      api-key: ${OPENAI_API_KEY}
    #      # Use only if you route through an internal gateway / proxy:
    #      base-url: ${OPENAI_BASE_URL:https://api.openai.com}
    #      # Optional metadata headers (only if your environment needs them)
    #      # organization-id: ${OPENAI_ORG:}
    #      # project-id: ${OPENAI_PROJECT:}
    #      chat:
    #        options:
    #          # Pin a model explicitly (choose what you actually use)
    #          model: ${OPENAI_CHAT_MODEL:gpt-4.1-mini}
    #          temperature: ${OPENAI_TEMPERATURE:0.2}
    #          # If your Spring AI version supports it:
    #          max-tokens: ${OPENAI_MAX_TOKENS:800}
    #          # top-p: ${OPENAI_TOP_P:1.0}
    model:
      embedding: ollama
    ollama:
      base-url: http://localhost:11434
      init:
        pull-model-strategy: never
        timeout: 5m
        max-retries: 0
      chat:
        options:
          model: phi3:14b
          num-ctx: 4096 # input context window
          num-predict: 256 # max generated tokens
          temperature: 0.7
          keep-alive: 15m
          ### Sampling controls (Top-K and Top-P)
          # Nucleus sampling
          top-p: 0.8
          # Top-k sampling, restricts sampling to the top K most likely next tokens.
          top-k: 40
      embedding:
        options:
          model: nomic-embed-text # alt. mxbai-embed-large
          keep-alive: 15m

    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
            schema: classpath:schema.sql
    vectorstore:
      pgvector:
        initialize-schema: true
        schema-name: public
        table-name: vector_store
        index-type: hnsw
        distance-type: cosine_distance
        dimensions: 768
logging:
  level:
    root: INFO
    gr.codelearn: TRACE
    org.springframework: INFO
    org.springframework.ai: INFO